/* Bezopt WASM bridge — client-side vectorizer.
 *
 * Mirrors the /api/* JSON contracts from ui/server.py + ui/bezopt_bridge.py,
 * but runs the native C++ pipeline directly in the browser via WebAssembly.
 * No server, no request size limits, no timeouts.
 *
 * Usage:
 *   const bezopt = new BezoptWasm();
 *   await bezopt.init();           // loads bezopt.js/wasm
 *   const result = bezopt.preprocess(payload);  // same shape as POST /api/preprocess
 */

"use strict";

// Struct memory layouts for wasm32 (generated by wasm/gen_layout.c).
const BEZOPT_LAYOUT = {"bezopt_rgb8_view":{"size":32,"fields":{"rgb":{"offset":0,"type":"ptr"},"width":{"offset":4,"type":"size_t"},"height":{"offset":8,"type":"size_t"},"row_stride_bytes":{"offset":12,"type":"size_t"},"color_space":{"offset":16,"type":"u32"},"initial_labels":{"offset":20,"type":"ptr"},"label_row_stride":{"offset":24,"type":"size_t"},"initial_region_count":{"offset":28,"type":"u32"}}},"bezopt_preprocess_options":{"size":56,"fields":{"target_regions":{"offset":0,"type":"u32"},"criterion":{"offset":4,"type":"u32"},"iterations":{"offset":8,"type":"u32"},"area_exponent":{"offset":16,"type":"f64"},"area_smallness_scale":{"offset":24,"type":"f64"},"area_raster_bias":{"offset":32,"type":"f64"},"saliency_weight":{"offset":40,"type":"f64"},"topology_weight":{"offset":48,"type":"f64"}}},"bezopt_preprocess_region":{"size":48,"fields":{"id":{"offset":0,"type":"u32"},"source_id":{"offset":4,"type":"u32"},"pixel_count":{"offset":8,"type":"u64"},"perimeter":{"offset":16,"type":"f64"},"centroid_x":{"offset":24,"type":"f64"},"centroid_y":{"offset":32,"type":"f64"},"touches_border":{"offset":40,"type":"i32"}}},"bezopt_preprocess_edge":{"size":32,"fields":{"left":{"offset":0,"type":"u32"},"right":{"offset":4,"type":"u32"},"shared_boundary":{"offset":8,"type":"f64"},"protected_boundary":{"offset":16,"type":"f64"},"locked_raster_edges":{"offset":24,"type":"u32"}}},"bezopt_preprocess_result":{"size":88,"fields":{"status":{"offset":0,"type":"u32"},"width":{"offset":4,"type":"size_t"},"height":{"offset":8,"type":"size_t"},"channels":{"offset":12,"type":"size_t"},"initial_regions":{"offset":16,"type":"u32"},"final_regions":{"offset":20,"type":"u32"},"lambda_star":{"offset":24,"type":"f64"},"elapsed_ms":{"offset":32,"type":"f64"},"target_reached":{"offset":40,"type":"i32"},"labels":{"offset":44,"type":"ptr"},"label_count":{"offset":48,"type":"size_t"},"regions":{"offset":52,"type":"ptr"},"region_count":{"offset":56,"type":"size_t"},"mean_colors":{"offset":60,"type":"ptr"},"mean_color_count":{"offset":64,"type":"size_t"},"edges":{"offset":68,"type":"ptr"},"edge_count":{"offset":72,"type":"size_t"},"merge_history":{"offset":76,"type":"ptr"},"merge_count":{"offset":80,"type":"size_t"}}},"bezopt_label_raster_view":{"size":36,"fields":{"labels":{"offset":0,"type":"ptr"},"width":{"offset":4,"type":"size_t"},"height":{"offset":8,"type":"size_t"},"label_row_stride":{"offset":12,"type":"size_t"},"region_count":{"offset":16,"type":"u32"},"region_linear_rgb":{"offset":20,"type":"ptr"},"region_color_stride":{"offset":24,"type":"size_t"},"pixel_srgb8":{"offset":28,"type":"ptr"},"pixel_srgb_row_stride_bytes":{"offset":32,"type":"size_t"}}},"bezopt_fit_options":{"size":136,"fields":{"coordinate_scale":{"offset":0,"type":"f64"},"max_error_px":{"offset":8,"type":"f64"},"residual_sigmas":{"offset":16,"type":"f64"},"excursion_sigmas":{"offset":24,"type":"f64"},"samples_per_cubic":{"offset":32,"type":"u32"},"reparameterization_iterations":{"offset":36,"type":"u32"},"corner_angle_degrees":{"offset":40,"type":"f64"},"corner_window":{"offset":48,"type":"u32"},"corner_run_edges":{"offset":52,"type":"u32"},"corner_scale_octaves":{"offset":56,"type":"u32"},"corner_scale_growth":{"offset":64,"type":"f64"},"guide_smoothing":{"offset":72,"type":"f64"},"topology_retries":{"offset":80,"type":"u32"},"preserve_topology":{"offset":84,"type":"i32"},"max_cubics_per_chain":{"offset":88,"type":"u32"},"max_total_cubics":{"offset":96,"type":"u64"},"contrast_floor":{"offset":104,"type":"f64"},"threads":{"offset":112,"type":"i32"},"refine_subpixel":{"offset":116,"type":"i32"},"max_subpixel_offset_px":{"offset":120,"type":"f64"},"subpixel_anchor_weight":{"offset":128,"type":"f64"}}},"bezopt_sample":{"size":56,"fields":{"segment":{"offset":0,"type":"u32"},"t":{"offset":8,"type":"f64"},"x":{"offset":16,"type":"f64"},"y":{"offset":24,"type":"f64"},"nx":{"offset":32,"type":"f64"},"ny":{"offset":40,"type":"f64"},"weight":{"offset":48,"type":"f64"}}},"bezopt_chain":{"size":36,"fields":{"control_xy":{"offset":0,"type":"ptr"},"control_point_count":{"offset":4,"type":"size_t"},"samples":{"offset":8,"type":"ptr"},"sample_count":{"offset":12,"type":"size_t"},"left_region":{"offset":16,"type":"u32"},"right_region":{"offset":20,"type":"u32"},"closed":{"offset":24,"type":"i32"},"corner_knots":{"offset":28,"type":"ptr"},"corner_knot_count":{"offset":32,"type":"size_t"}}},"bezopt_fit_chain":{"size":44,"fields":{"control_point_offset":{"offset":0,"type":"size_t"},"control_point_count":{"offset":4,"type":"size_t"},"sample_offset":{"offset":8,"type":"size_t"},"sample_count":{"offset":12,"type":"size_t"},"left_region":{"offset":16,"type":"u32"},"right_region":{"offset":20,"type":"u32"},"closed":{"offset":24,"type":"i32"},"source_point_offset":{"offset":28,"type":"size_t"},"source_point_count":{"offset":32,"type":"size_t"},"corner_knot_offset":{"offset":36,"type":"size_t"},"corner_knot_count":{"offset":40,"type":"size_t"}}},"bezopt_fit_report":{"size":256,"fields":{"status":{"offset":0,"type":"u32"},"raster_boundary_edges":{"offset":8,"type":"u64"},"raw_vertices":{"offset":16,"type":"u64"},"pinned_vertices":{"offset":24,"type":"u64"},"open_chains":{"offset":32,"type":"u64"},"closed_chains":{"offset":40,"type":"u64"},"cubics":{"offset":48,"type":"u64"},"target_samples":{"offset":56,"type":"u64"},"topology_refits":{"offset":64,"type":"u32"},"recovered_chains":{"offset":72,"type":"u64"},"grid_fallback_chains":{"offset":80,"type":"u64"},"grid_fallback_cubics":{"offset":88,"type":"u64"},"grid_fallback_length_px":{"offset":96,"type":"f64"},"unconstrained_cubics":{"offset":104,"type":"u64"},"unconstrained_length_px":{"offset":112,"type":"f64"},"curve_to_contour_px":{"offset":120,"type":"f64"},"max_curve_to_contour_px":{"offset":128,"type":"f64"},"contour_to_curve_px":{"offset":136,"type":"f64"},"accepted_error_px":{"offset":144,"type":"f64"},"prepare_ms":{"offset":152,"type":"f64"},"trace_ms":{"offset":160,"type":"f64"},"fit_ms":{"offset":168,"type":"f64"},"elapsed_ms":{"offset":176,"type":"f64"},"used_grid_fallback":{"offset":184,"type":"i32"},"subpixel_edges":{"offset":192,"type":"u64"},"mean_abs_subpixel_offset_px":{"offset":200,"type":"f64"},"max_abs_subpixel_offset_px":{"offset":208,"type":"f64"},"mean_edge_confidence":{"offset":216,"type":"f64"},"detected_corners":{"offset":224,"type":"u64"},"smoothed_guide_vertices":{"offset":232,"type":"u64"},"mean_guide_displacement_px":{"offset":240,"type":"f64"},"max_guide_displacement_px":{"offset":248,"type":"f64"}}},"bezopt_fit_result":{"size":296,"fields":{"report":{"offset":0,"type":"inline"},"chains":{"offset":256,"type":"ptr"},"chain_count":{"offset":260,"type":"size_t"},"control_xy":{"offset":264,"type":"ptr"},"control_point_count":{"offset":268,"type":"size_t"},"samples":{"offset":272,"type":"ptr"},"sample_count":{"offset":276,"type":"size_t"},"source_xy":{"offset":280,"type":"ptr"},"source_point_count":{"offset":284,"type":"size_t"},"corner_knots":{"offset":288,"type":"ptr"},"corner_knot_count":{"offset":292,"type":"size_t"}}},"bezopt_options":{"size":160,"fields":{"max_sweeps":{"offset":0,"type":"u32"},"local_iterations":{"offset":4,"type":"u32"},"lbfgs_history":{"offset":8,"type":"u32"},"coarse_sample_stride":{"offset":12,"type":"u32"},"threads":{"offset":16,"type":"i32"},"normalization":{"offset":20,"type":"u32"},"coordinate_scale":{"offset":24,"type":"f64"},"data_weight":{"offset":32,"type":"f64"},"tangent_weight":{"offset":40,"type":"f64"},"robust_delta_px":{"offset":48,"type":"f64"},"angle_weight":{"offset":56,"type":"f64"},"handle_weight":{"offset":64,"type":"f64"},"length_weight":{"offset":72,"type":"f64"},"angle_epsilon_rad":{"offset":80,"type":"f64"},"handle_epsilon_px":{"offset":88,"type":"f64"},"max_step_px":{"offset":96,"type":"f64"},"gradient_tolerance":{"offset":104,"type":"f64"},"relative_tolerance":{"offset":112,"type":"f64"},"max_line_search_steps":{"offset":120,"type":"u32"},"reproject_samples":{"offset":124,"type":"i32"},"projection_iterations":{"offset":128,"type":"u32"},"preserve_topology":{"offset":132,"type":"i32"},"topology_retries":{"offset":136,"type":"u32"},"topology_flatness_px":{"offset":144,"type":"f64"},"topology_cell_size_px":{"offset":152,"type":"f64"}}},"bezopt_report":{"size":88,"fields":{"status":{"offset":0,"type":"u32"},"sweeps":{"offset":4,"type":"u32"},"blocks_optimized":{"offset":8,"type":"u64"},"function_evaluations":{"offset":16,"type":"u64"},"sample_evaluations":{"offset":24,"type":"u64"},"topology_rejections":{"offset":32,"type":"u32"},"initial_energy":{"offset":40,"type":"f64"},"final_energy":{"offset":48,"type":"f64"},"initial_normal_rmse_px":{"offset":56,"type":"f64"},"final_normal_rmse_px":{"offset":64,"type":"f64"},"elapsed_ms":{"offset":72,"type":"f64"},"converged":{"offset":80,"type":"i32"}}},"bezopt_raster_view":{"size":44,"fields":{"labels":{"offset":0,"type":"ptr"},"width":{"offset":4,"type":"size_t"},"height":{"offset":8,"type":"size_t"},"label_row_stride":{"offset":12,"type":"size_t"},"region_count":{"offset":16,"type":"u32"},"region_linear_rgb":{"offset":20,"type":"ptr"},"region_color_stride":{"offset":24,"type":"size_t"},"source_srgb8":{"offset":28,"type":"ptr"},"source_srgb_row_stride_bytes":{"offset":32,"type":"size_t"},"optimized_region_rgb":{"offset":36,"type":"ptr"},"optimized_region_color_stride":{"offset":40,"type":"size_t"}}},"bezopt_raster_options":{"size":32,"fields":{"samples_per_axis":{"offset":0,"type":"u32"},"band_height_px":{"offset":4,"type":"u32"},"threads":{"offset":8,"type":"i32"},"color_space":{"offset":12,"type":"u32"},"fixed_initial_length_px":{"offset":16,"type":"f64"},"max_transition_error_ratio":{"offset":24,"type":"f64"}}},"bezopt_raster_report":{"size":112,"fields":{"status":{"offset":0,"type":"u32"},"subpixel_samples":{"offset":8,"type":"u64"},"cubic_tests":{"offset":16,"type":"u64"},"crossings":{"offset":24,"type":"u64"},"transition_errors":{"offset":32,"type":"u64"},"bands":{"offset":40,"type":"u32"},"initial_length_px":{"offset":48,"type":"f64"},"squared_error":{"offset":56,"type":"f64"},"yang_data_energy":{"offset":64,"type":"f64"},"mse":{"offset":72,"type":"f64"},"psnr_db":{"offset":80,"type":"f64"},"index_ms":{"offset":88,"type":"f64"},"render_ms":{"offset":96,"type":"f64"},"elapsed_ms":{"offset":104,"type":"f64"}}},"bezopt_raster_result":{"size":120,"fields":{"report":{"offset":0,"type":"inline"},"srgb8":{"offset":112,"type":"ptr"},"srgb8_size":{"offset":116,"type":"size_t"}}},"bezopt_raster_optimize_options":{"size":192,"fields":{"max_sweeps":{"offset":0,"type":"u32"},"samples_per_axis":{"offset":4,"type":"u32"},"band_height_px":{"offset":8,"type":"u32"},"threads":{"offset":12,"type":"i32"},"color_space":{"offset":16,"type":"u32"},"fixed_initial_length_px":{"offset":24,"type":"f64"},"geometry_solver":{"offset":32,"type":"u32"},"normalization":{"offset":36,"type":"u32"},"coordinate_scale":{"offset":40,"type":"f64"},"step_scale":{"offset":48,"type":"f64"},"hessian_damping":{"offset":56,"type":"f64"},"max_step_px":{"offset":64,"type":"f64"},"max_line_search_steps":{"offset":72,"type":"u32"},"relative_tolerance":{"offset":80,"type":"f64"},"angle_weight":{"offset":88,"type":"f64"},"handle_weight":{"offset":96,"type":"f64"},"length_weight":{"offset":104,"type":"f64"},"angle_epsilon_rad":{"offset":112,"type":"f64"},"handle_epsilon_px":{"offset":120,"type":"f64"},"active_margin_px":{"offset":128,"type":"f64"},"preserve_topology":{"offset":136,"type":"i32"},"topology_flatness_px":{"offset":144,"type":"f64"},"topology_cell_size_px":{"offset":152,"type":"f64"},"optimize_region_colors":{"offset":160,"type":"i32"},"color_solve_iterations":{"offset":164,"type":"u32"},"color_regularization":{"offset":168,"type":"f64"},"color_tolerance":{"offset":176,"type":"f64"},"block_schedule":{"offset":184,"type":"u32"}}},"bezopt_raster_optimize_report":{"size":216,"fields":{"status":{"offset":0,"type":"u32"},"sweeps":{"offset":4,"type":"u32"},"line_search_evaluations":{"offset":8,"type":"u32"},"topology_rejections":{"offset":12,"type":"u32"},"active_pixels":{"offset":16,"type":"u64"},"subpixel_samples":{"offset":24,"type":"u64"},"cubic_tests":{"offset":32,"type":"u64"},"gradient_intervals":{"offset":40,"type":"u64"},"geometry_blocks":{"offset":48,"type":"u64"},"geometry_batches":{"offset":56,"type":"u64"},"block_solve_fallbacks":{"offset":64,"type":"u64"},"initial_length_px":{"offset":72,"type":"f64"},"initial_active_squared_error":{"offset":80,"type":"f64"},"final_active_squared_error":{"offset":88,"type":"f64"},"initial_data_energy":{"offset":96,"type":"f64"},"final_data_energy":{"offset":104,"type":"f64"},"initial_prior_energy":{"offset":112,"type":"f64"},"final_prior_energy":{"offset":120,"type":"f64"},"initial_objective":{"offset":128,"type":"f64"},"final_objective":{"offset":136,"type":"f64"},"maximum_control_step_px":{"offset":144,"type":"f64"},"color_solves":{"offset":152,"type":"u32"},"color_solve_iterations":{"offset":156,"type":"u32"},"initial_full_squared_error":{"offset":160,"type":"f64"},"final_full_squared_error":{"offset":168,"type":"f64"},"initial_full_data_energy":{"offset":176,"type":"f64"},"final_full_data_energy":{"offset":184,"type":"f64"},"maximum_color_change":{"offset":192,"type":"f64"},"elapsed_ms":{"offset":200,"type":"f64"},"converged":{"offset":208,"type":"i32"}}},"bezopt_svg_view":{"size":24,"fields":{"width":{"offset":0,"type":"size_t"},"height":{"offset":4,"type":"size_t"},"region_count":{"offset":8,"type":"u32"},"region_srgb":{"offset":12,"type":"ptr"},"region_color_stride":{"offset":16,"type":"size_t"},"region_touches_frame":{"offset":20,"type":"ptr"}}},"bezopt_svg_report":{"size":24,"fields":{"status":{"offset":0,"type":"u32"},"region_count":{"offset":4,"type":"u32"},"loop_count":{"offset":8,"type":"u32"},"path_count":{"offset":12,"type":"u32"},"elapsed_ms":{"offset":16,"type":"f64"}}},"bezopt_svg_result":{"size":32,"fields":{"report":{"offset":0,"type":"inline"},"svg_utf8":{"offset":24,"type":"ptr"},"svg_utf8_size":{"offset":28,"type":"size_t"}}}};

class BezoptWasmError extends Error {}

// Enum mappings (mirror ui/bezopt_bridge.py).
const PREPROCESS_CRITERIA = { bg: 0, ms: 1, scale: 2, area: 3 };
const PREPROCESS_COLOR_SPACES = { rgb: 0, linear: 1, lab: 2, oklab: 3 };
const RASTER_COLOR_SPACES = { srgb: 0, linear: 1 };
const RASTER_GEOMETRY_SOLVERS = { diagonal: 0, overlapping_blocks: 1 };
const RASTER_BLOCK_SCHEDULES = { additive: 0, colored_multiplicative: 1 };
const RASTER_NORMALIZATION_MODES = { none: 0, yang: 1 };
const OPTIMIZER_NORMALIZATION_MODES = { none: 0, yang: 1, scale: 2 };

const MAX_CHAINS = 50000;
const MAX_CONTROL_POINTS = 2000000;
const MAX_SAMPLES = 5000000;

class BezoptWasm {
  constructor() {
    this.Module = null;
    this.ready = false;
    this._view = null;
  }

  async init() {
    if (this.ready) return;
    await new Promise((resolve, reject) => {
      // If the factory is already available (e.g. loaded via module import), use it.
      if (typeof createBezoptModule === "function") { resolve(); return; }
      const script = document.createElement("script");
      script.src = "bezopt.js";
      script.onload = resolve;
      script.onerror = () => reject(new BezoptWasmError("failed to load bezopt.js"));
      document.head.appendChild(script);
    });
    if (typeof createBezoptModule === "function") {
      // Modularized build: factory returns the initialized Module.
      this.Module = await createBezoptModule();
    } else {
      // Classic build: global Module with onRuntimeInitialized.
      await new Promise((resolve, reject) => {
        const Module = window.Module || {};
        Module.onRuntimeInitialized = () => { this.Module = Module; resolve(); };
        Module.onAbort = (msg) => reject(new BezoptWasmError("WASM aborted: " + msg));
        if (Module.calledRun) { this.Module = Module; resolve(); }
      });
    }
    this._view = new DataView(this.Module.HEAPU8.buffer);
    this.ready = true;
    this._refreshView();
  }

  _refreshView() {
    if (this.Module && this._view.buffer !== this.Module.HEAPU8.buffer) {
      this._view = new DataView(this.Module.HEAPU8.buffer);
    }
  }

  _malloc(size) {
    this._refreshView();
    const ptr = this.Module._malloc(size);
    if (!ptr) throw new BezoptWasmError("WASM out of memory");
    return ptr;
  }

  _free(ptr) {
    if (ptr) this.Module._free(ptr);
  }

  _writeBytes(ptr, bytes) {
    this._refreshView();
    this.Module.HEAPU8.set(bytes, ptr);
  }

  _readBytes(ptr, size) {
    this._refreshView();
    return this.Module.HEAPU8.slice(ptr, ptr + size);
  }

  _getField(layoutName, fieldName) {
    const layout = BEZOPT_LAYOUT[layoutName];
    const field = layout.fields[fieldName];
    if (!field) throw new BezoptWasmError(`unknown field ${layoutName}.${fieldName}`);
    return field;
  }

  _writeField(ptr, layoutName, fieldName, value) {
    const field = this._getField(layoutName, fieldName);
    const offset = ptr + field.offset;
    this._refreshView();
    const v = this._view;
    switch (field.type) {
      case "u32": v.setUint32(offset, value >>> 0, true); break;
      case "i32": v.setInt32(offset, value | 0, true); break;
      case "u64": v.setBigUint64(offset, BigInt(value), true); break;
      case "f64": v.setFloat64(offset, value, true); break;
      case "size_t": v.setUint32(offset, value >>> 0, true); break;
      case "ptr": v.setUint32(offset, value >>> 0, true); break;
      default: throw new BezoptWasmError(`unsupported field type ${field.type}`);
    }
  }

  _readField(ptr, layoutName, fieldName) {
    const field = this._getField(layoutName, fieldName);
    const offset = ptr + field.offset;
    this._refreshView();
    const v = this._view;
    switch (field.type) {
      case "u32": return v.getUint32(offset, true);
      case "i32": return v.getInt32(offset, true);
      case "u64": return Number(v.getBigUint64(offset, true));
      case "f64": return v.getFloat64(offset, true);
      case "size_t": return v.getUint32(offset, true);
      case "ptr": return v.getUint32(offset, true);
      default: throw new BezoptWasmError(`unsupported field type ${field.type}`);
    }
  }

  _structSize(layoutName) {
    return BEZOPT_LAYOUT[layoutName].size;
  }

  _statusString(fn, status) {
    const buf = this._malloc(256);
    try {
      this.Module[fn](status, buf, 256);
      this._refreshView();
      const bytes = this.Module.HEAPU8.subarray(buf, buf + 256);
      let len = 0;
      while (len < 256 && bytes[len] !== 0) len++;
      return new TextDecoder().decode(bytes.subarray(0, len));
    } finally {
      this._free(buf);
    }
  }

  // ---- validation helpers (mirror bezopt_bridge.py) ----

  _integer(value, label, minimum, maximum) {
    if (typeof value !== "number" || !Number.isInteger(value)) {
      throw new BezoptWasmError(`${label} must be an integer`);
    }
    if (value < minimum || value > maximum) {
      throw new BezoptWasmError(`${label} is out of range`);
    }
    return value;
  }

  _finiteNumber(value, label) {
    if (typeof value === "boolean") throw new BezoptWasmError(`${label} must be numeric`);
    const n = Number(value);
    if (!Number.isFinite(n)) throw new BezoptWasmError(`${label} must be finite`);
    return n;
  }

  _base64ToBytes(value, label) {
    if (typeof value !== "string" || !value) {
      throw new BezoptWasmError(`${label} must be non-empty base64`);
    }
    const binary = atob(value);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return bytes;
  }

  _bytesToBase64(bytes) {
    let binary = "";
    const chunk = 8192;
    for (let i = 0; i < bytes.length; i += chunk) {
      binary += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk));
    }
    return btoa(binary);
  }

  _uint32FromBase64(value, count) {
    const bytes = this._base64ToBytes(value, "labels");
    if (bytes.length !== count * 4) throw new BezoptWasmError("label buffer has wrong size");
    return new Uint32Array(bytes.buffer, bytes.byteOffset, count);
  }

  // ---- options builders ----

  _makePreprocessOptions(overrides) {
    const ptr = this._malloc(this._structSize("bezopt_preprocess_options"));
    this.Module._wasm_default_preprocess_options(ptr);
    if (overrides) {
      if (typeof overrides !== "object") throw new BezoptWasmError("options must be an object");
      const known = new Set(["target_regions", "criterion", "iterations",
        "area_exponent", "area_smallness_scale", "area_raster_bias",
        "saliency_weight", "topology_weight"]);
      for (const name of Object.keys(overrides)) {
        if (!known.has(name)) throw new BezoptWasmError(`unknown preprocessor option: ${name}`);
      }
      if (overrides.target_regions !== undefined)
        this._writeField(ptr, "bezopt_preprocess_options", "target_regions",
          this._integer(overrides.target_regions, "options.target_regions", 1, 4294967295));
      if (overrides.criterion !== undefined) {
        if (!(overrides.criterion in PREPROCESS_CRITERIA))
          throw new BezoptWasmError("options.criterion is unknown");
        this._writeField(ptr, "bezopt_preprocess_options", "criterion",
          PREPROCESS_CRITERIA[overrides.criterion]);
      }
      if (overrides.iterations !== undefined)
        this._writeField(ptr, "bezopt_preprocess_options", "iterations",
          this._integer(overrides.iterations, "options.iterations", 1, 4294967295));
      for (const name of ["area_exponent", "area_smallness_scale", "area_raster_bias",
                          "saliency_weight", "topology_weight"]) {
        if (overrides[name] !== undefined)
          this._writeField(ptr, "bezopt_preprocess_options", name,
            this._finiteNumber(overrides[name], `options.${name}`));
      }
    }
    return ptr;
  }

  // ---- /api/preprocess ----

  preprocess(payload) {
    if (typeof payload !== "object" || !payload) throw new BezoptWasmError("request body must be an object");
    const width = this._integer(payload.width, "width", 1, 2147483647);
    const height = this._integer(payload.height, "height", 1, 2147483647);
    const pixels = width * height;
    const rgb = this._base64ToBytes(payload.rgb_base64, "rgb_base64");
    if (rgb.length !== pixels * 3) throw new BezoptWasmError("rgb_base64 has the wrong byte length");
    const colorSpaceName = payload.color_space || "rgb";
    if (!(colorSpaceName in PREPROCESS_COLOR_SPACES)) throw new BezoptWasmError("color_space is unknown");

    let labelPtr = 0, labelRowStride = 0;
    let initialRegionCount = this._integer(payload.initial_region_count || 0, "initial_region_count", 0, 4294967295);
    const allocations = [];
    try {
      const rgbPtr = this._malloc(rgb.length);
      allocations.push(rgbPtr);
      this._writeBytes(rgbPtr, rgb);

      if (payload.initial_labels_base64) {
        const labels = this._uint32FromBase64(payload.initial_labels_base64, pixels);
        labelPtr = this._malloc(labels.byteLength);
        allocations.push(labelPtr);
        this._writeBytes(labelPtr, new Uint8Array(labels.buffer, labels.byteOffset, labels.byteLength));
        labelRowStride = width;
      } else if (initialRegionCount !== 0) {
        throw new BezoptWasmError("initial_region_count requires initial labels");
      }

      const viewPtr = this._malloc(this._structSize("bezopt_rgb8_view"));
      allocations.push(viewPtr);
      this._writeField(viewPtr, "bezopt_rgb8_view", "rgb", rgbPtr);
      this._writeField(viewPtr, "bezopt_rgb8_view", "width", width);
      this._writeField(viewPtr, "bezopt_rgb8_view", "height", height);
      this._writeField(viewPtr, "bezopt_rgb8_view", "row_stride_bytes", width * 3);
      this._writeField(viewPtr, "bezopt_rgb8_view", "color_space", PREPROCESS_COLOR_SPACES[colorSpaceName]);
      this._writeField(viewPtr, "bezopt_rgb8_view", "initial_labels", labelPtr);
      this._writeField(viewPtr, "bezopt_rgb8_view", "label_row_stride", labelRowStride);
      this._writeField(viewPtr, "bezopt_rgb8_view", "initial_region_count", initialRegionCount);

      const optPtr = this._makePreprocessOptions(payload.options);
      allocations.push(optPtr);
      const resultPtr = this._malloc(this._structSize("bezopt_preprocess_result"));
      allocations.push(resultPtr);

      const status = this.Module._bezopt_preprocess_rgb8(viewPtr, optPtr, resultPtr);
      const statusText = this._statusString("_wasm_preprocess_status_string", status);
      if (status !== 0) throw new BezoptWasmError(`native preprocessor returned ${statusText}`);

      const outWidth = this._readField(resultPtr, "bezopt_preprocess_result", "width");
      const outHeight = this._readField(resultPtr, "bezopt_preprocess_result", "height");
      const channels = this._readField(resultPtr, "bezopt_preprocess_result", "channels");
      const labelsPtr = this._readField(resultPtr, "bezopt_preprocess_result", "labels");
      const labelCount = this._readField(resultPtr, "bezopt_preprocess_result", "label_count");
      const regionsPtr = this._readField(resultPtr, "bezopt_preprocess_result", "regions");
      const regionCount = this._readField(resultPtr, "bezopt_preprocess_result", "region_count");
      const meanColorsPtr = this._readField(resultPtr, "bezopt_preprocess_result", "mean_colors");
      const edgesPtr = this._readField(resultPtr, "bezopt_preprocess_result", "edges");
      const edgeCount = this._readField(resultPtr, "bezopt_preprocess_result", "edge_count");

      const labelBytes = this._readBytes(labelsPtr, labelCount * 4);
      const regionSize = this._structSize("bezopt_preprocess_region");
      const edgeSize = this._structSize("bezopt_preprocess_edge");
      const regions = [];
      for (let i = 0; i < regionCount; i++) {
        const rp = regionsPtr + i * regionSize;
        const meanColor = [];
        for (let c = 0; c < channels; c++) {
          this._refreshView();
          meanColor.push(this._view.getFloat64(meanColorsPtr + (i * channels + c) * 8, true));
        }
        regions.push({
          id: this._readField(rp, "bezopt_preprocess_region", "id"),
          source_id: this._readField(rp, "bezopt_preprocess_region", "source_id"),
          pixel_count: this._readField(rp, "bezopt_preprocess_region", "pixel_count"),
          perimeter: this._readField(rp, "bezopt_preprocess_region", "perimeter"),
          centroid: [
            this._readField(rp, "bezopt_preprocess_region", "centroid_x"),
            this._readField(rp, "bezopt_preprocess_region", "centroid_y"),
          ],
          touches_border: !!this._readField(rp, "bezopt_preprocess_region", "touches_border"),
          mean_color: meanColor,
        });
      }
      const edges = [];
      for (let i = 0; i < edgeCount; i++) {
        const ep = edgesPtr + i * edgeSize;
        edges.push({
          left: this._readField(ep, "bezopt_preprocess_edge", "left"),
          right: this._readField(ep, "bezopt_preprocess_edge", "right"),
          shared_boundary: this._readField(ep, "bezopt_preprocess_edge", "shared_boundary"),
          protected_boundary: this._readField(ep, "bezopt_preprocess_edge", "protected_boundary"),
          locked_raster_edges: this._readField(ep, "bezopt_preprocess_edge", "locked_raster_edges"),
        });
      }

      const result = {
        width: outWidth,
        height: outHeight,
        labels_base64: this._bytesToBase64(labelBytes),
        regions,
        edges,
        report: {
          status: this._readField(resultPtr, "bezopt_preprocess_result", "status"),
          status_text: statusText,
          initial_regions: this._readField(resultPtr, "bezopt_preprocess_result", "initial_regions"),
          final_regions: this._readField(resultPtr, "bezopt_preprocess_result", "final_regions"),
          rag_edges: edgeCount,
          merges: this._readField(resultPtr, "bezopt_preprocess_result", "merge_count"),
          lambda_star: this._readField(resultPtr, "bezopt_preprocess_result", "lambda_star"),
          elapsed_ms: this._readField(resultPtr, "bezopt_preprocess_result", "elapsed_ms"),
          target_reached: !!this._readField(resultPtr, "bezopt_preprocess_result", "target_reached"),
        },
      };
      this.Module._bezopt_free_preprocess_result(resultPtr);
      return result;
    } finally {
      for (const ptr of allocations) this._free(ptr);
    }
  }

  _makeFitOptions(overrides) {
    const ptr = this._malloc(this._structSize("bezopt_fit_options"));
    this.Module._wasm_default_fit_options(ptr);
    if (overrides) {
      if (typeof overrides !== "object") throw new BezoptWasmError("options must be an object");
      const uintFields = new Set(["samples_per_cubic", "reparameterization_iterations",
        "corner_window", "corner_run_edges", "corner_scale_octaves", "topology_retries",
        "max_cubics_per_chain"]);
      const doubleFields = new Set(["coordinate_scale", "max_error_px", "residual_sigmas",
        "excursion_sigmas", "corner_angle_degrees", "corner_scale_growth", "guide_smoothing",
        "contrast_floor", "max_subpixel_offset_px", "subpixel_anchor_weight"]);
      const boolFields = new Set(["preserve_topology", "refine_subpixel"]);
      const known = new Set([...uintFields, ...doubleFields, ...boolFields,
        "max_total_cubics", "threads"]);
      for (const name of Object.keys(overrides)) {
        if (!known.has(name)) throw new BezoptWasmError(`unknown fitter option: ${name}`);
      }
      for (const name of uintFields) {
        if (overrides[name] !== undefined) {
          const min = (name === "reparameterization_iterations" || name === "topology_retries" ||
                       name === "corner_run_edges" || name === "corner_scale_octaves") ? 0 : 1;
          this._writeField(ptr, "bezopt_fit_options", name,
            this._integer(overrides[name], `options.${name}`, min, 4294967295));
        }
      }
      if (overrides.max_total_cubics !== undefined)
        this._writeField(ptr, "bezopt_fit_options", "max_total_cubics",
          this._integer(overrides.max_total_cubics, "options.max_total_cubics", 1, 9007199254740991));
      for (const name of doubleFields) {
        if (overrides[name] !== undefined)
          this._writeField(ptr, "bezopt_fit_options", name,
            this._finiteNumber(overrides[name], `options.${name}`));
      }
      for (const name of boolFields) {
        if (overrides[name] !== undefined) {
          if (typeof overrides[name] !== "boolean") throw new BezoptWasmError(`options.${name} must be boolean`);
          this._writeField(ptr, "bezopt_fit_options", name, overrides[name] ? 1 : 0);
        }
      }
      if (overrides.threads !== undefined)
        this._writeField(ptr, "bezopt_fit_options", "threads",
          this._integer(overrides.threads, "options.threads", -2147483648, 2147483647));
    }
    return ptr;
  }

  // ---- /api/fit ----

  fit(payload) {
    if (typeof payload !== "object" || !payload) throw new BezoptWasmError("request body must be an object");
    const width = this._integer(payload.width, "width", 1, 2147483647);
    const height = this._integer(payload.height, "height", 1, 2147483647);
    const pixels = width * height;
    const labels = this._uint32FromBase64(payload.labels_base64, pixels);
    const regionCount = this._integer(payload.region_count, "region_count", 1, 4294967295);

    const allocations = [];
    try {
      const labelPtr = this._malloc(labels.byteLength);
      allocations.push(labelPtr);
      this._writeBytes(labelPtr, new Uint8Array(labels.buffer, labels.byteOffset, labels.byteLength));

      let colorPtr = 0, colorStride = 0;
      if (payload.region_linear_rgb) {
        if (!Array.isArray(payload.region_linear_rgb) || payload.region_linear_rgb.length !== regionCount * 3)
          throw new BezoptWasmError("region_linear_rgb must contain three values per region");
        const colors = payload.region_linear_rgb.map((v, i) => this._finiteNumber(v, `region_linear_rgb[${i}]`));
        if (colors.some(v => v < 0 || v > 1)) throw new BezoptWasmError("region_linear_rgb values must be in [0,1]");
        colorPtr = this._malloc(colors.length * 8);
        allocations.push(colorPtr);
        this._refreshView();
        for (let i = 0; i < colors.length; i++) this._view.setFloat64(colorPtr + i * 8, colors[i], true);
        colorStride = 3;
      }

      let rgbPtr = 0, rgbStride = 0;
      if (payload.rgb_base64) {
        const rgb = this._base64ToBytes(payload.rgb_base64, "rgb_base64");
        if (rgb.length !== pixels * 3) throw new BezoptWasmError("rgb_base64 has the wrong byte length");
        rgbPtr = this._malloc(rgb.length);
        allocations.push(rgbPtr);
        this._writeBytes(rgbPtr, rgb);
        rgbStride = width * 3;
      }

      const viewPtr = this._malloc(this._structSize("bezopt_label_raster_view"));
      allocations.push(viewPtr);
      this._writeField(viewPtr, "bezopt_label_raster_view", "labels", labelPtr);
      this._writeField(viewPtr, "bezopt_label_raster_view", "width", width);
      this._writeField(viewPtr, "bezopt_label_raster_view", "height", height);
      this._writeField(viewPtr, "bezopt_label_raster_view", "label_row_stride", width);
      this._writeField(viewPtr, "bezopt_label_raster_view", "region_count", regionCount);
      this._writeField(viewPtr, "bezopt_label_raster_view", "region_linear_rgb", colorPtr);
      this._writeField(viewPtr, "bezopt_label_raster_view", "region_color_stride", colorStride);
      this._writeField(viewPtr, "bezopt_label_raster_view", "pixel_srgb8", rgbPtr);
      this._writeField(viewPtr, "bezopt_label_raster_view", "pixel_srgb_row_stride_bytes", rgbStride);

      const optPtr = this._makeFitOptions(payload.options);
      allocations.push(optPtr);
      const resultPtr = this._malloc(this._structSize("bezopt_fit_result"));
      allocations.push(resultPtr);

      const status = this.Module._bezopt_fit_boundaries(viewPtr, optPtr, resultPtr);
      const statusText = this._statusString("_wasm_fit_status_string", status);
      if (status !== 0) throw new BezoptWasmError(`native fitter returned ${statusText}`);

      const chainCount = this._readField(resultPtr, "bezopt_fit_result", "chain_count");
      if (chainCount > MAX_CHAINS) throw new BezoptWasmError("fitted chain limit exceeded");
      const controlPointCount = this._readField(resultPtr, "bezopt_fit_result", "control_point_count");
      if (controlPointCount > MAX_CONTROL_POINTS) throw new BezoptWasmError("fitted control-point limit exceeded");
      const sampleCount = this._readField(resultPtr, "bezopt_fit_result", "sample_count");
      if (sampleCount > MAX_SAMPLES) throw new BezoptWasmError("fitted sample limit exceeded");

      const chainsPtr = this._readField(resultPtr, "bezopt_fit_result", "chains");
      const controlXyPtr = this._readField(resultPtr, "bezopt_fit_result", "control_xy");
      const samplesPtr = this._readField(resultPtr, "bezopt_fit_result", "samples");
      const sourceXyPtr = this._readField(resultPtr, "bezopt_fit_result", "source_xy");
      const cornerKnotsPtr = this._readField(resultPtr, "bezopt_fit_result", "corner_knots");

      const chainSize = this._structSize("bezopt_fit_chain");
      const sampleSize = this._structSize("bezopt_sample");
      const chains = [];
      for (let ci = 0; ci < chainCount; ci++) {
        const cp = chainsPtr + ci * chainSize;
        const controlOffset = this._readField(cp, "bezopt_fit_chain", "control_point_offset");
        const controlCount = this._readField(cp, "bezopt_fit_chain", "control_point_count");
        const sampleOffset = this._readField(cp, "bezopt_fit_chain", "sample_offset");
        const sampleN = this._readField(cp, "bezopt_fit_chain", "sample_count");
        const sourceOffset = this._readField(cp, "bezopt_fit_chain", "source_point_offset");
        const sourceCount = this._readField(cp, "bezopt_fit_chain", "source_point_count");
        const cornerOffset = this._readField(cp, "bezopt_fit_chain", "corner_knot_offset");
        const cornerCount = this._readField(cp, "bezopt_fit_chain", "corner_knot_count");

        this._refreshView();
        const controls = [];
        for (let i = 0; i < controlCount; i++) {
          controls.push([
            this._view.getFloat64(controlXyPtr + (controlOffset + i) * 16, true),
            this._view.getFloat64(controlXyPtr + (controlOffset + i) * 16 + 8, true),
          ]);
        }
        const samples = [];
        for (let i = 0; i < sampleN; i++) {
          const sp = samplesPtr + (sampleOffset + i) * sampleSize;
          samples.push({
            segment: this._readField(sp, "bezopt_sample", "segment"),
            t: this._readField(sp, "bezopt_sample", "t"),
            point: [this._readField(sp, "bezopt_sample", "x"), this._readField(sp, "bezopt_sample", "y")],
            normal: [this._readField(sp, "bezopt_sample", "nx"), this._readField(sp, "bezopt_sample", "ny")],
            weight: this._readField(sp, "bezopt_sample", "weight"),
          });
        }
        const sourcePoints = [];
        for (let i = 0; i < sourceCount; i++) {
          sourcePoints.push([
            this._view.getFloat64(sourceXyPtr + (sourceOffset + i) * 16, true),
            this._view.getFloat64(sourceXyPtr + (sourceOffset + i) * 16 + 8, true),
          ]);
        }
        const cornerKnots = [];
        for (let i = 0; i < cornerCount; i++) {
          cornerKnots.push(this._view.getUint32(cornerKnotsPtr + (cornerOffset + i) * 4, true));
        }
        chains.push({
          control_points: controls,
          samples,
          source_points: sourcePoints,
          corner_knots: cornerKnots,
          left_region: this._readField(cp, "bezopt_fit_chain", "left_region"),
          right_region: this._readField(cp, "bezopt_fit_chain", "right_region"),
          closed: !!this._readField(cp, "bezopt_fit_chain", "closed"),
        });
      }

      const reportPtr = resultPtr; // report is inline at offset 0
      const result = {
        chains,
        target_diagnostics: this._targetCorrespondenceDiagnostics(chains),
        report: {
          status: this._readField(reportPtr, "bezopt_fit_report", "status"),
          status_text: statusText,
          raster_boundary_edges: this._readField(reportPtr, "bezopt_fit_report", "raster_boundary_edges"),
          raw_vertices: this._readField(reportPtr, "bezopt_fit_report", "raw_vertices"),
          pinned_vertices: this._readField(reportPtr, "bezopt_fit_report", "pinned_vertices"),
          open_chains: this._readField(reportPtr, "bezopt_fit_report", "open_chains"),
          closed_chains: this._readField(reportPtr, "bezopt_fit_report", "closed_chains"),
          cubics: this._readField(reportPtr, "bezopt_fit_report", "cubics"),
          target_samples: this._readField(reportPtr, "bezopt_fit_report", "target_samples"),
          topology_refits: this._readField(reportPtr, "bezopt_fit_report", "topology_refits"),
          recovered_chains: this._readField(reportPtr, "bezopt_fit_report", "recovered_chains"),
          grid_fallback_cubics: this._readField(reportPtr, "bezopt_fit_report", "grid_fallback_cubics"),
          unconstrained_cubics: this._readField(reportPtr, "bezopt_fit_report", "unconstrained_cubics"),
          curve_to_contour_px: this._readField(reportPtr, "bezopt_fit_report", "curve_to_contour_px"),
          max_curve_to_contour_px: this._readField(reportPtr, "bezopt_fit_report", "max_curve_to_contour_px"),
          contour_to_curve_px: this._readField(reportPtr, "bezopt_fit_report", "contour_to_curve_px"),
          unconstrained_length_px: this._readField(reportPtr, "bezopt_fit_report", "unconstrained_length_px"),
          grid_fallback_length_px: this._readField(reportPtr, "bezopt_fit_report", "grid_fallback_length_px"),
          grid_fallback_chains: this._readField(reportPtr, "bezopt_fit_report", "grid_fallback_chains"),
          accepted_error_px: this._readField(reportPtr, "bezopt_fit_report", "accepted_error_px"),
          prepare_ms: this._readField(reportPtr, "bezopt_fit_report", "prepare_ms"),
          trace_ms: this._readField(reportPtr, "bezopt_fit_report", "trace_ms"),
          fit_ms: this._readField(reportPtr, "bezopt_fit_report", "fit_ms"),
          elapsed_ms: this._readField(reportPtr, "bezopt_fit_report", "elapsed_ms"),
          used_grid_fallback: !!this._readField(reportPtr, "bezopt_fit_report", "used_grid_fallback"),
          subpixel_edges: this._readField(reportPtr, "bezopt_fit_report", "subpixel_edges"),
          mean_abs_subpixel_offset_px: this._readField(reportPtr, "bezopt_fit_report", "mean_abs_subpixel_offset_px"),
          mean_edge_confidence: this._readField(reportPtr, "bezopt_fit_report", "mean_edge_confidence"),
          max_abs_subpixel_offset_px: this._readField(reportPtr, "bezopt_fit_report", "max_abs_subpixel_offset_px"),
          detected_corners: this._readField(reportPtr, "bezopt_fit_report", "detected_corners"),
          smoothed_guide_vertices: this._readField(reportPtr, "bezopt_fit_report", "smoothed_guide_vertices"),
          mean_guide_displacement_px: this._readField(reportPtr, "bezopt_fit_report", "mean_guide_displacement_px"),
          max_guide_displacement_px: this._readField(reportPtr, "bezopt_fit_report", "max_guide_displacement_px"),
        },
      };
      this.Module._bezopt_free_fit_result(resultPtr);
      return result;
    } finally {
      for (const ptr of allocations) this._free(ptr);
    }
  }

  _targetCorrespondenceDiagnostics(chains) {
    // Port of bezopt_bridge.py::_target_correspondence_diagnostics.
    const parameterEpsilon = 1e-9, pointEpsilon = 1e-7;
    let sampleCount = 0, segmentCount = 0, emptySegments = 0, invalidSegments = 0;
    let clampedParameters = 0, coincidentParameters = 0, collapsedDistinctParameters = 0;
    let reversedParameters = 0, segmentOrderReversals = 0, segmentSkips = 0;
    let assignmentEuclideanOver1px = 0, assignmentNormalOver1px = 0;
    const joinGaps = [], knotSampleGaps = [], euclideanResiduals = [], normalResiduals = [];
    const dist = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1]);
    const cubicPoint = (points, t) => {
      const u = 1 - t, b0 = u*u*u, b1 = 3*u*u*t, b2 = 3*u*t*t, b3 = t*t*t;
      return [b0*points[0][0]+b1*points[1][0]+b2*points[2][0]+b3*points[3][0],
              b0*points[0][1]+b1*points[1][1]+b2*points[2][1]+b3*points[3][1]];
    };
    for (const chain of chains) {
      const controls = chain.control_points, closed = chain.closed;
      const segments = closed ? controls.length / 3 : (controls.length - 1) / 3;
      segmentCount += segments;
      const bySegment = Array.from({length: segments}, () => []);
      let previousSegment = null;
      for (const sample of chain.samples) {
        sampleCount++;
        const segment = sample.segment | 0;
        if (segment < 0 || segment >= segments) { invalidSegments++; continue; }
        if (previousSegment !== null) {
          if (segment < previousSegment) segmentOrderReversals++;
          else if (segment > previousSegment + 1) segmentSkips++;
        }
        previousSegment = segment;
        bySegment[segment].push(sample);
        const t = sample.t;
        if (t <= parameterEpsilon || t >= 1 - parameterEpsilon) clampedParameters++;
        const base = 3 * segment;
        const points = [0,1,2,3].map(i => controls[(base + i) % controls.length]);
        const assigned = cubicPoint(points, t);
        const dx = assigned[0] - sample.point[0], dy = assigned[1] - sample.point[1];
        const euclideanResidual = Math.hypot(dx, dy);
        const normalResidual = Math.abs(dx * sample.normal[0] + dy * sample.normal[1]);
        euclideanResiduals.push(euclideanResidual);
        normalResiduals.push(normalResidual);
        if (euclideanResidual > 1) assignmentEuclideanOver1px++;
        if (normalResidual > 1) assignmentNormalOver1px++;
      }
      for (const samples of bySegment) {
        if (!samples.length) { emptySegments++; continue; }
        for (let i = 1; i < samples.length; i++) {
          const deltaT = samples[i].t - samples[i-1].t;
          if (deltaT < -parameterEpsilon) reversedParameters++;
          else if (Math.abs(deltaT) <= parameterEpsilon) {
            if (dist(samples[i-1].point, samples[i].point) > pointEpsilon) collapsedDistinctParameters++;
            else coincidentParameters++;
          }
        }
      }
      for (let s = 0; s < segments; s++) {
        const samples = bySegment[s];
        if (!samples.length) continue;
        const base = 3 * s;
        knotSampleGaps.push(dist(controls[base % controls.length], samples[0].point));
        knotSampleGaps.push(dist(controls[(base+3) % controls.length], samples[samples.length-1].point));
      }
      const joinPairs = closed ? segments : Math.max(0, segments - 1);
      for (let s = 0; s < joinPairs; s++) {
        const ns = (s + 1) % segments;
        if (bySegment[s].length && bySegment[ns].length)
          joinGaps.push(dist(bySegment[s][bySegment[s].length-1].point, bySegment[ns][0].point));
      }
    }
    const percentile = (values, q) => {
      if (!values.length) return null;
      const ordered = [...values].sort((a,b) => a-b);
      const pos = (ordered.length - 1) * q;
      const lo = Math.floor(pos), hi = Math.ceil(pos);
      if (lo === hi) return ordered[lo];
      const f = pos - lo;
      return ordered[lo] * (1 - f) + ordered[hi] * f;
    };
    const summary = (values) => ({
      count: values.length,
      median_px: percentile(values, 0.5),
      p95_px: percentile(values, 0.95),
      max_px: values.length ? Math.max(...values) : null,
    });
    return {
      sample_count: sampleCount, segment_count: segmentCount, empty_segments: emptySegments,
      invalid_segments: invalidSegments, clamped_parameters: clampedParameters,
      coincident_parameters: coincidentParameters, collapsed_distinct_parameters: collapsedDistinctParameters,
      reversed_parameters: reversedParameters, segment_order_reversals: segmentOrderReversals,
      segment_skips: segmentSkips, assignment_euclidean_over_1px: assignmentEuclideanOver1px,
      assignment_normal_over_1px: assignmentNormalOver1px,
      target_join_gap: summary(joinGaps), knot_sample_gap: summary(knotSampleGaps),
      assignment_euclidean_residual: summary(euclideanResiduals),
      assignment_normal_residual: summary(normalResiduals),
    };
  }

  _pair(value, label) {
    if (!Array.isArray(value) || value.length !== 2)
      throw new BezoptWasmError(`${label} must be [x, y]`);
    return [this._finiteNumber(value[0], `${label}[0]`), this._finiteNumber(value[1], `${label}[1]`)];
  }

  // Build native bezopt_chain array from JS chain objects. Returns {chainPtr, chainCount, keepalive[]}.
  // The caller must free chainPtr and keep the keepalive buffers alive during the call.
  _buildNativeChains(chainsInput, regionCount, withSamples) {
    if (!Array.isArray(chainsInput)) throw new BezoptWasmError("chains must be an array");
    if (chainsInput.length > MAX_CHAINS) throw new BezoptWasmError("chain limit exceeded");
    const keepalive = [];
    const chainSize = this._structSize("bezopt_chain");
    const sampleSize = this._structSize("bezopt_sample");
    const chainPtr = this._malloc(chainsInput.length * chainSize);
    keepalive.push({ free: () => this._free(chainPtr) });
    let totalControls = 0, totalSamples = 0;

    chainsInput.forEach((chainInput, chainIndex) => {
      const label = `chains[${chainIndex}]`;
      if (typeof chainInput !== "object" || !chainInput) throw new BezoptWasmError(`${label} must be an object`);
      const pointsInput = chainInput.control_points;
      if (!Array.isArray(pointsInput) || !pointsInput.length)
        throw new BezoptWasmError(`${label}.control_points must be a non-empty array`);
      const flat = [];
      pointsInput.forEach((pt, pi) => {
        const [x, y] = this._pair(pt, `${label}.control_points[${pi}]`);
        flat.push(x, y);
      });
      totalControls += pointsInput.length;
      if (totalControls > MAX_CONTROL_POINTS) throw new BezoptWasmError("control-point limit exceeded");
      const controlPtr = this._malloc(flat.length * 8);
      keepalive.push({ free: () => this._free(controlPtr) });
      this._refreshView();
      for (let i = 0; i < flat.length; i++) this._view.setFloat64(controlPtr + i * 8, flat[i], true);

      let samplePtr = 0, sampleCount = 0;
      if (withSamples) {
        const samplesInput = chainInput.samples || [];
        if (!Array.isArray(samplesInput)) throw new BezoptWasmError(`${label}.samples must be an array`);
        sampleCount = samplesInput.length;
        totalSamples += sampleCount;
        if (totalSamples > MAX_SAMPLES) throw new BezoptWasmError("sample limit exceeded");
        if (sampleCount > 0) {
          samplePtr = this._malloc(sampleCount * sampleSize);
          keepalive.push({ free: () => this._free(samplePtr) });
          samplesInput.forEach((s, si) => {
            const sl = `${label}.samples[${si}]`;
            if (typeof s !== "object" || !s) throw new BezoptWasmError(`${sl} must be an object`);
            const sp = samplePtr + si * sampleSize;
            this._writeField(sp, "bezopt_sample", "segment", this._integer(s.segment, `${sl}.segment`, 0, 4294967295));
            this._writeField(sp, "bezopt_sample", "t", this._finiteNumber(s.t, `${sl}.t`));
            const [x, y] = this._pair(s.point, `${sl}.point`);
            const [nx, ny] = this._pair(s.normal, `${sl}.normal`);
            this._writeField(sp, "bezopt_sample", "x", x);
            this._writeField(sp, "bezopt_sample", "y", y);
            this._writeField(sp, "bezopt_sample", "nx", nx);
            this._writeField(sp, "bezopt_sample", "ny", ny);
            this._writeField(sp, "bezopt_sample", "weight", this._finiteNumber(s.weight !== undefined ? s.weight : 1.0, `${sl}.weight`));
          });
        }
      }

      const closed = chainInput.closed || false;
      if (typeof closed !== "boolean") throw new BezoptWasmError(`${label}.closed must be boolean`);
      const segmentCount = closed ? (pointsInput.length / 3 | 0) : ((pointsInput.length - 1) / 3 | 0);
      let cornerPtr = 0, cornerCount = 0;
      const cornerInput = chainInput.corner_knots || [];
      if (!Array.isArray(cornerInput)) throw new BezoptWasmError(`${label}.corner_knots must be a list`);
      cornerCount = cornerInput.length;
      if (cornerCount > 0) {
        cornerPtr = this._malloc(cornerCount * 4);
        keepalive.push({ free: () => this._free(cornerPtr) });
        this._refreshView();
        cornerInput.forEach((v, i) => {
          this._view.setUint32(cornerPtr + i * 4,
            this._integer(v, `${label}.corner_knots[${i}]`, 0, Math.max(segmentCount - 1, 0)), true);
        });
      }

      const cp = chainPtr + chainIndex * chainSize;
      this._writeField(cp, "bezopt_chain", "control_xy", controlPtr);
      this._writeField(cp, "bezopt_chain", "control_point_count", pointsInput.length);
      this._writeField(cp, "bezopt_chain", "samples", samplePtr);
      this._writeField(cp, "bezopt_chain", "sample_count", sampleCount);
      this._writeField(cp, "bezopt_chain", "left_region",
        this._integer(chainInput.left_region, `${label}.left_region`, 0, regionCount - 1));
      this._writeField(cp, "bezopt_chain", "right_region",
        this._integer(chainInput.right_region, `${label}.right_region`, 0, regionCount - 1));
      this._writeField(cp, "bezopt_chain", "closed", closed ? 1 : 0);
      this._writeField(cp, "bezopt_chain", "corner_knots", cornerPtr);
      this._writeField(cp, "bezopt_chain", "corner_knot_count", cornerCount);
    });

    return { chainPtr, chainCount: chainsInput.length, keepalive, totalControls, totalSamples };
  }

  _readNativeChainControls(chainPtr, chainIndex, pointCount) {
    const chainSize = this._structSize("bezopt_chain");
    const cp = chainPtr + chainIndex * chainSize;
    const controlPtr = this._readField(cp, "bezopt_chain", "control_xy");
    this._refreshView();
    const points = [];
    for (let i = 0; i < pointCount; i++) {
      points.push([
        this._view.getFloat64(controlPtr + i * 16, true),
        this._view.getFloat64(controlPtr + i * 16 + 8, true),
      ]);
    }
    return points;
  }

  _makeOptimizerOptions(overrides) {
    const ptr = this._malloc(this._structSize("bezopt_options"));
    this.Module._wasm_default_options(ptr);
    if (overrides) {
      if (typeof overrides !== "object") throw new BezoptWasmError("options must be an object");
      const uintFields = new Set(["max_sweeps", "local_iterations", "lbfgs_history",
        "coarse_sample_stride", "max_line_search_steps", "projection_iterations", "topology_retries"]);
      const doubleFields = new Set(["coordinate_scale", "data_weight", "tangent_weight",
        "robust_delta_px", "angle_weight", "handle_weight", "length_weight",
        "angle_epsilon_rad", "handle_epsilon_px", "max_step_px",
        "gradient_tolerance", "relative_tolerance", "topology_flatness_px", "topology_cell_size_px"]);
      const boolFields = new Set(["reproject_samples", "preserve_topology"]);
      const known = new Set([...uintFields, ...doubleFields, ...boolFields, "threads", "normalization"]);
      for (const name of Object.keys(overrides)) {
        if (!known.has(name)) throw new BezoptWasmError(`unknown optimizer option: ${name}`);
      }
      for (const name of uintFields) {
        if (overrides[name] !== undefined)
          this._writeField(ptr, "bezopt_options", name,
            this._integer(overrides[name], `options.${name}`, 0, 4294967295));
      }
      for (const name of doubleFields) {
        if (overrides[name] !== undefined)
          this._writeField(ptr, "bezopt_options", name,
            this._finiteNumber(overrides[name], `options.${name}`));
      }
      for (const name of boolFields) {
        if (overrides[name] !== undefined) {
          if (typeof overrides[name] !== "boolean") throw new BezoptWasmError(`options.${name} must be boolean`);
          this._writeField(ptr, "bezopt_options", name, overrides[name] ? 1 : 0);
        }
      }
      if (overrides.normalization !== undefined) {
        if (!(overrides.normalization in OPTIMIZER_NORMALIZATION_MODES))
          throw new BezoptWasmError("options.normalization is unknown");
        this._writeField(ptr, "bezopt_options", "normalization",
          OPTIMIZER_NORMALIZATION_MODES[overrides.normalization]);
      }
      if (overrides.threads !== undefined)
        this._writeField(ptr, "bezopt_options", "threads",
          this._integer(overrides.threads, "options.threads", -2147483648, 2147483647));
    }
    return ptr;
  }

  // ---- /api/optimize ----

  optimize(payload) {
    if (typeof payload !== "object" || !payload) throw new BezoptWasmError("request body must be an object");
    const chainsInput = payload.chains;
    if (!Array.isArray(chainsInput) || !chainsInput.length) throw new BezoptWasmError("chains must be a non-empty array");
    // regionCount for validation: use max region id + 1
    let regionCount = 1;
    for (const c of chainsInput) {
      regionCount = Math.max(regionCount, (c.left_region | 0) + 1, (c.right_region | 0) + 1);
    }

    const { chainPtr, chainCount, keepalive, totalControls, totalSamples } =
      this._buildNativeChains(chainsInput, regionCount, true);
    const optPtr = this._makeOptimizerOptions(payload.options);
    const reportPtr = this._malloc(this._structSize("bezopt_report"));
    try {
      const status = this.Module._bezopt_optimize(chainPtr, chainCount, optPtr, reportPtr);
      const statusText = this._statusString("_wasm_status_string", status);
      if (status !== 0) throw new BezoptWasmError(`native optimizer returned ${statusText}`);

      const outputChains = chainsInput.map((chainInput, i) => ({
        control_points: this._readNativeChainControls(chainPtr, i, chainInput.control_points.length),
      }));
      return {
        chains: outputChains,
        report: {
          status: this._readField(reportPtr, "bezopt_report", "status"),
          status_text: statusText,
          sweeps: this._readField(reportPtr, "bezopt_report", "sweeps"),
          blocks_optimized: this._readField(reportPtr, "bezopt_report", "blocks_optimized"),
          function_evaluations: this._readField(reportPtr, "bezopt_report", "function_evaluations"),
          sample_evaluations: this._readField(reportPtr, "bezopt_report", "sample_evaluations"),
          topology_rejections: this._readField(reportPtr, "bezopt_report", "topology_rejections"),
          initial_energy: this._readField(reportPtr, "bezopt_report", "initial_energy"),
          final_energy: this._readField(reportPtr, "bezopt_report", "final_energy"),
          initial_normal_rmse_px: this._readField(reportPtr, "bezopt_report", "initial_normal_rmse_px"),
          final_normal_rmse_px: this._readField(reportPtr, "bezopt_report", "final_normal_rmse_px"),
          elapsed_ms: this._readField(reportPtr, "bezopt_report", "elapsed_ms"),
          converged: !!this._readField(reportPtr, "bezopt_report", "converged"),
        },
        problem_size: { chains: chainCount, control_points: totalControls, samples: totalSamples },
      };
    } finally {
      this._free(reportPtr);
      this._free(optPtr);
      for (const k of keepalive) k.free();
    }
  }

  _makeRasterOptions(overrides) {
    const ptr = this._malloc(this._structSize("bezopt_raster_options"));
    this.Module._wasm_default_raster_options(ptr);
    if (overrides) {
      if (typeof overrides !== "object") throw new BezoptWasmError("options must be an object");
      const known = new Set(["samples_per_axis", "band_height_px", "threads", "color_space",
        "fixed_initial_length_px", "max_transition_error_ratio"]);
      for (const name of Object.keys(overrides)) {
        if (!known.has(name)) throw new BezoptWasmError(`unknown raster option: ${name}`);
      }
      if (overrides.samples_per_axis !== undefined)
        this._writeField(ptr, "bezopt_raster_options", "samples_per_axis",
          this._integer(overrides.samples_per_axis, "options.samples_per_axis", 1, 32));
      if (overrides.band_height_px !== undefined)
        this._writeField(ptr, "bezopt_raster_options", "band_height_px",
          this._integer(overrides.band_height_px, "options.band_height_px", 1, 4294967295));
      if (overrides.fixed_initial_length_px !== undefined)
        this._writeField(ptr, "bezopt_raster_options", "fixed_initial_length_px",
          this._finiteNumber(overrides.fixed_initial_length_px, "options.fixed_initial_length_px"));
      if (overrides.max_transition_error_ratio !== undefined)
        this._writeField(ptr, "bezopt_raster_options", "max_transition_error_ratio",
          this._finiteNumber(overrides.max_transition_error_ratio, "options.max_transition_error_ratio"));
      if (overrides.color_space !== undefined) {
        if (!(overrides.color_space in RASTER_COLOR_SPACES))
          throw new BezoptWasmError("options.color_space is unknown");
        this._writeField(ptr, "bezopt_raster_options", "color_space",
          RASTER_COLOR_SPACES[overrides.color_space]);
      }
      if (overrides.threads !== undefined)
        this._writeField(ptr, "bezopt_raster_options", "threads",
          this._integer(overrides.threads, "options.threads", 0, 2147483647));
    }
    return ptr;
  }

  _buildRasterView(payload, width, height, pixels) {
    // Returns {viewPtr, keepalive[]} for bezopt_raster_view.
    const keepalive = [];
    const labels = this._uint32FromBase64(payload.labels_base64, pixels);
    const labelPtr = this._malloc(labels.byteLength);
    keepalive.push({ free: () => this._free(labelPtr) });
    this._writeBytes(labelPtr, new Uint8Array(labels.buffer, labels.byteOffset, labels.byteLength));

    const regionCount = this._integer(payload.region_count, "region_count", 1, 4294967295);
    if (!Array.isArray(payload.region_linear_rgb) || payload.region_linear_rgb.length !== regionCount * 3)
      throw new BezoptWasmError("region_linear_rgb must contain three values per region");
    const colors = payload.region_linear_rgb.map((v, i) => this._finiteNumber(v, `region_linear_rgb[${i}]`));
    if (colors.some(v => v < 0 || v > 1)) throw new BezoptWasmError("region_linear_rgb values must be in [0,1]");
    const colorPtr = this._malloc(colors.length * 8);
    keepalive.push({ free: () => this._free(colorPtr) });
    this._refreshView();
    for (let i = 0; i < colors.length; i++) this._view.setFloat64(colorPtr + i * 8, colors[i], true);

    let sourcePtr = 0, sourceStride = 0;
    if (payload.rgb_base64) {
      const source = this._base64ToBytes(payload.rgb_base64, "rgb_base64");
      if (source.length !== pixels * 3) throw new BezoptWasmError("rgb_base64 has the wrong byte length");
      sourcePtr = this._malloc(source.length);
      keepalive.push({ free: () => this._free(sourcePtr) });
      this._writeBytes(sourcePtr, source);
      sourceStride = width * 3;
    }

    const viewPtr = this._malloc(this._structSize("bezopt_raster_view"));
    keepalive.push({ free: () => this._free(viewPtr) });
    this._writeField(viewPtr, "bezopt_raster_view", "labels", labelPtr);
    this._writeField(viewPtr, "bezopt_raster_view", "width", width);
    this._writeField(viewPtr, "bezopt_raster_view", "height", height);
    this._writeField(viewPtr, "bezopt_raster_view", "label_row_stride", width);
    this._writeField(viewPtr, "bezopt_raster_view", "region_count", regionCount);
    this._writeField(viewPtr, "bezopt_raster_view", "region_linear_rgb", colorPtr);
    this._writeField(viewPtr, "bezopt_raster_view", "region_color_stride", 3);
    this._writeField(viewPtr, "bezopt_raster_view", "source_srgb8", sourcePtr);
    this._writeField(viewPtr, "bezopt_raster_view", "source_srgb_row_stride_bytes", sourceStride);
    this._writeField(viewPtr, "bezopt_raster_view", "optimized_region_rgb", 0);
    this._writeField(viewPtr, "bezopt_raster_view", "optimized_region_color_stride", 0);
    return { viewPtr, keepalive, regionCount };
  }

  // ---- /api/render-reference ----

  render_reference(payload) {
    if (typeof payload !== "object" || !payload) throw new BezoptWasmError("request body must be an object");
    const width = this._integer(payload.width, "width", 1, 2147483647);
    const height = this._integer(payload.height, "height", 1, 2147483647);
    const pixels = width * height;

    const { viewPtr, keepalive, regionCount } = this._buildRasterView(payload, width, height, pixels);
    const { chainPtr, chainCount, keepalive: chainKeep } =
      this._buildNativeChains(payload.chains || [], regionCount, false);
    const optPtr = this._makeRasterOptions(payload.options);
    const resultPtr = this._malloc(this._structSize("bezopt_raster_result"));
    try {
      const status = this.Module._bezopt_render_reference(chainPtr, chainCount, viewPtr, optPtr, resultPtr);
      const statusText = this._statusString("_wasm_raster_status_string", status);
      const transitionErrors = this._readField(resultPtr, "bezopt_raster_report", "transition_errors");
      const crossings = this._readField(resultPtr, "bezopt_raster_report", "crossings");
      if (status !== 0)
        throw new BezoptWasmError(`native rasterizer returned ${statusText} (${transitionErrors} of ${crossings} crossings inconsistent)`);
      const srgb8Ptr = this._readField(resultPtr, "bezopt_raster_result", "srgb8");
      const srgb8Size = this._readField(resultPtr, "bezopt_raster_result", "srgb8_size");
      if (srgb8Size !== pixels * 3 || !srgb8Ptr)
        throw new BezoptWasmError("native rasterizer returned an invalid image buffer");
      const raw = this._readBytes(srgb8Ptr, srgb8Size);
      const psnr = this._readField(resultPtr, "bezopt_raster_report", "psnr_db");
      const result = {
        width, height,
        rgb_base64: this._bytesToBase64(raw),
        report: {
          status: this._readField(resultPtr, "bezopt_raster_report", "status"),
          status_text: statusText,
          subpixel_samples: this._readField(resultPtr, "bezopt_raster_report", "subpixel_samples"),
          cubic_tests: this._readField(resultPtr, "bezopt_raster_report", "cubic_tests"),
          crossings,
          transition_errors: transitionErrors,
          bands: this._readField(resultPtr, "bezopt_raster_report", "bands"),
          initial_length_px: this._readField(resultPtr, "bezopt_raster_report", "initial_length_px"),
          squared_error: this._readField(resultPtr, "bezopt_raster_report", "squared_error"),
          yang_data_energy: this._readField(resultPtr, "bezopt_raster_report", "yang_data_energy"),
          mse: this._readField(resultPtr, "bezopt_raster_report", "mse"),
          psnr_db: Number.isFinite(psnr) ? psnr : null,
          index_ms: this._readField(resultPtr, "bezopt_raster_report", "index_ms"),
          render_ms: this._readField(resultPtr, "bezopt_raster_report", "render_ms"),
          elapsed_ms: this._readField(resultPtr, "bezopt_raster_report", "elapsed_ms"),
        },
      };
      this.Module._bezopt_free_raster_result(resultPtr);
      return result;
    } finally {
      this._free(resultPtr);
      this._free(optPtr);
      for (const k of chainKeep) k.free();
      for (const k of keepalive) k.free();
    }
  }

  // ---- /api/export-flat-svg ----

  export_flat_svg(payload) {
    if (typeof payload !== "object" || !payload) throw new BezoptWasmError("request body must be an object");
    const width = this._integer(payload.width, "width", 1, 2147483647);
    const height = this._integer(payload.height, "height", 1, 2147483647);
    const regionCount = this._integer(payload.region_count, "region_count", 1, 4294967295);
    if (!Array.isArray(payload.region_linear_rgb) || payload.region_linear_rgb.length !== regionCount * 3)
      throw new BezoptWasmError("region_linear_rgb must contain three values per region");
    const colors = payload.region_linear_rgb.map((v, i) => this._finiteNumber(v, `region_linear_rgb[${i}]`));
    if (colors.some(v => v < 0 || v > 1)) throw new BezoptWasmError("region_linear_rgb values must be in [0,1]");

    const keepalive = [];
    try {
      const colorPtr = this._malloc(colors.length * 8);
      keepalive.push({ free: () => this._free(colorPtr) });
      this._refreshView();
      for (let i = 0; i < colors.length; i++) this._view.setFloat64(colorPtr + i * 8, colors[i], true);

      let touchesPtr = 0;
      if (payload.region_touches_frame) {
        if (!Array.isArray(payload.region_touches_frame) || payload.region_touches_frame.length !== regionCount)
          throw new BezoptWasmError("region_touches_frame must contain one value per region");
        touchesPtr = this._malloc(regionCount);
        keepalive.push({ free: () => this._free(touchesPtr) });
        this._refreshView();
        payload.region_touches_frame.forEach((v, i) => {
          let b;
          if (typeof v === "boolean") b = v ? 1 : 0;
          else if (v === 0 || v === 1) b = v;
          else throw new BezoptWasmError(`region_touches_frame[${i}] must be 0, 1, or boolean`);
          this._view.setUint8(touchesPtr + i, b);
        });
      }

      if (!Array.isArray(payload.chains) || !payload.chains.length)
        throw new BezoptWasmError("chains must be a non-empty array");
      const { chainPtr, chainCount, keepalive: chainKeep } =
        this._buildNativeChains(payload.chains, regionCount, false);

      const viewPtr = this._malloc(this._structSize("bezopt_svg_view"));
      keepalive.push({ free: () => this._free(viewPtr) });
      this._writeField(viewPtr, "bezopt_svg_view", "width", width);
      this._writeField(viewPtr, "bezopt_svg_view", "height", height);
      this._writeField(viewPtr, "bezopt_svg_view", "region_count", regionCount);
      this._writeField(viewPtr, "bezopt_svg_view", "region_srgb", colorPtr);
      this._writeField(viewPtr, "bezopt_svg_view", "region_color_stride", 3);
      this._writeField(viewPtr, "bezopt_svg_view", "region_touches_frame", touchesPtr);

      const resultPtr = this._malloc(this._structSize("bezopt_svg_result"));
      keepalive.push({ free: () => this._free(resultPtr) });
      const status = this.Module._bezopt_export_flat_svg(chainPtr, chainCount, viewPtr, resultPtr);
      const statusText = this._statusString("_wasm_raster_status_string", status);
      if (status !== 0) throw new BezoptWasmError(`native svg exporter returned ${statusText}`);
      const svgPtr = this._readField(resultPtr, "bezopt_svg_result", "svg_utf8");
      const svgSize = this._readField(resultPtr, "bezopt_svg_result", "svg_utf8_size");
      if (!svgPtr || svgSize === 0) throw new BezoptWasmError("native svg exporter returned an empty document");
      const svgBytes = this._readBytes(svgPtr, svgSize);
      const svgText = new TextDecoder().decode(svgBytes);
      const result = {
        width, height,
        svg: svgText,
        report: {
          status: this._readField(resultPtr, "bezopt_svg_report", "status"),
          status_text: statusText,
          region_count: this._readField(resultPtr, "bezopt_svg_report", "region_count"),
          loop_count: this._readField(resultPtr, "bezopt_svg_report", "loop_count"),
          path_count: this._readField(resultPtr, "bezopt_svg_report", "path_count"),
          elapsed_ms: this._readField(resultPtr, "bezopt_svg_report", "elapsed_ms"),
        },
      };
      this.Module._bezopt_free_svg_result(resultPtr);
      for (const k of chainKeep) k.free();
      return result;
    } finally {
      for (const k of keepalive) k.free();
    }
  }

  _makeRasterOptimizeOptions(overrides) {
    const ptr = this._malloc(this._structSize("bezopt_raster_optimize_options"));
    this.Module._wasm_default_raster_optimize_options(ptr);
    if (overrides) {
      if (typeof overrides !== "object") throw new BezoptWasmError("options must be an object");
      const uintFields = new Set(["max_sweeps", "samples_per_axis", "band_height_px",
        "max_line_search_steps", "color_solve_iterations"]);
      const doubleFields = new Set(["coordinate_scale", "fixed_initial_length_px", "step_scale",
        "hessian_damping", "max_step_px", "relative_tolerance", "angle_weight", "handle_weight",
        "length_weight", "angle_epsilon_rad", "handle_epsilon_px", "active_margin_px",
        "topology_flatness_px", "topology_cell_size_px", "color_regularization", "color_tolerance"]);
      const boolFields = new Set(["preserve_topology", "optimize_region_colors"]);
      const known = new Set([...uintFields, ...doubleFields, ...boolFields,
        "threads", "color_space", "geometry_solver", "block_schedule", "normalization"]);
      for (const name of Object.keys(overrides)) {
        if (!known.has(name)) throw new BezoptWasmError(`unknown raster optimizer option: ${name}`);
      }
      for (const name of uintFields) {
        if (overrides[name] !== undefined) {
          const max = name === "samples_per_axis" ? 32 : 4294967295;
          this._writeField(ptr, "bezopt_raster_optimize_options", name,
            this._integer(overrides[name], `options.${name}`, 1, max));
        }
      }
      for (const name of doubleFields) {
        if (overrides[name] !== undefined)
          this._writeField(ptr, "bezopt_raster_optimize_options", name,
            this._finiteNumber(overrides[name], `options.${name}`));
      }
      for (const name of boolFields) {
        if (overrides[name] !== undefined) {
          if (typeof overrides[name] !== "boolean") throw new BezoptWasmError(`options.${name} must be boolean`);
          this._writeField(ptr, "bezopt_raster_optimize_options", name, overrides[name] ? 1 : 0);
        }
      }
      if (overrides.color_space !== undefined) {
        if (!(overrides.color_space in RASTER_COLOR_SPACES)) throw new BezoptWasmError("options.color_space is unknown");
        this._writeField(ptr, "bezopt_raster_optimize_options", "color_space", RASTER_COLOR_SPACES[overrides.color_space]);
      }
      if (overrides.geometry_solver !== undefined) {
        if (!(overrides.geometry_solver in RASTER_GEOMETRY_SOLVERS)) throw new BezoptWasmError("options.geometry_solver is unknown");
        this._writeField(ptr, "bezopt_raster_optimize_options", "geometry_solver", RASTER_GEOMETRY_SOLVERS[overrides.geometry_solver]);
      }
      if (overrides.block_schedule !== undefined) {
        if (!(overrides.block_schedule in RASTER_BLOCK_SCHEDULES)) throw new BezoptWasmError("options.block_schedule is unknown");
        this._writeField(ptr, "bezopt_raster_optimize_options", "block_schedule", RASTER_BLOCK_SCHEDULES[overrides.block_schedule]);
      }
      if (overrides.normalization !== undefined) {
        if (!(overrides.normalization in RASTER_NORMALIZATION_MODES)) throw new BezoptWasmError("options.normalization is unknown");
        this._writeField(ptr, "bezopt_raster_optimize_options", "normalization", RASTER_NORMALIZATION_MODES[overrides.normalization]);
      }
      if (overrides.threads !== undefined)
        this._writeField(ptr, "bezopt_raster_optimize_options", "threads",
          this._integer(overrides.threads, "options.threads", 0, 2147483647));
    }
    return ptr;
  }

  // ---- /api/optimize-raster ----

  optimize_raster(payload) {
    if (typeof payload !== "object" || !payload) throw new BezoptWasmError("request body must be an object");
    const width = this._integer(payload.width, "width", 1, 2147483647);
    const height = this._integer(payload.height, "height", 1, 2147483647);
    const pixels = width * height;

    const { viewPtr, keepalive, regionCount } = this._buildRasterView(payload, width, height, pixels);
    // optimize_raster requires rgb_base64 (source image)
    if (!payload.rgb_base64) throw new BezoptWasmError("rgb_base64 is required");
    if (!Array.isArray(payload.chains) || !payload.chains.length)
      throw new BezoptWasmError("chains must be a non-empty array");
    const { chainPtr, chainCount, keepalive: chainKeep, totalControls, totalSamples } =
      this._buildNativeChains(payload.chains, regionCount, true);
    const optPtr = this._makeRasterOptimizeOptions(payload.options);
    const reportPtr = this._malloc(this._structSize("bezopt_raster_optimize_report"));
    try {
      const status = this.Module._bezopt_optimize_raster(chainPtr, chainCount, viewPtr, optPtr, reportPtr);
      const statusText = this._statusString("_wasm_raster_status_string", status);
      if (status !== 0) throw new BezoptWasmError(`native raster optimizer returned ${statusText}`);

      const outputChains = payload.chains.map((chainInput, i) => ({
        control_points: this._readNativeChainControls(chainPtr, i, chainInput.control_points.length),
      }));
      const R = "bezopt_raster_optimize_report";
      return {
        chains: outputChains,
        report: {
          status: this._readField(reportPtr, R, "status"),
          status_text: statusText,
          sweeps: this._readField(reportPtr, R, "sweeps"),
          line_search_evaluations: this._readField(reportPtr, R, "line_search_evaluations"),
          topology_rejections: this._readField(reportPtr, R, "topology_rejections"),
          active_pixels: this._readField(reportPtr, R, "active_pixels"),
          subpixel_samples: this._readField(reportPtr, R, "subpixel_samples"),
          cubic_tests: this._readField(reportPtr, R, "cubic_tests"),
          gradient_intervals: this._readField(reportPtr, R, "gradient_intervals"),
          geometry_blocks: this._readField(reportPtr, R, "geometry_blocks"),
          geometry_batches: this._readField(reportPtr, R, "geometry_batches"),
          block_solve_fallbacks: this._readField(reportPtr, R, "block_solve_fallbacks"),
          initial_length_px: this._readField(reportPtr, R, "initial_length_px"),
          initial_active_squared_error: this._readField(reportPtr, R, "initial_active_squared_error"),
          final_active_squared_error: this._readField(reportPtr, R, "final_active_squared_error"),
          initial_data_energy: this._readField(reportPtr, R, "initial_data_energy"),
          final_data_energy: this._readField(reportPtr, R, "final_data_energy"),
          initial_prior_energy: this._readField(reportPtr, R, "initial_prior_energy"),
          final_prior_energy: this._readField(reportPtr, R, "final_prior_energy"),
          initial_objective: this._readField(reportPtr, R, "initial_objective"),
          final_objective: this._readField(reportPtr, R, "final_objective"),
          maximum_control_step_px: this._readField(reportPtr, R, "maximum_control_step_px"),
          color_solves: this._readField(reportPtr, R, "color_solves"),
          color_solve_iterations: this._readField(reportPtr, R, "color_solve_iterations"),
          initial_full_squared_error: this._readField(reportPtr, R, "initial_full_squared_error"),
          final_full_squared_error: this._readField(reportPtr, R, "final_full_squared_error"),
          initial_full_data_energy: this._readField(reportPtr, R, "initial_full_data_energy"),
          final_full_data_energy: this._readField(reportPtr, R, "final_full_data_energy"),
          maximum_color_change: this._readField(reportPtr, R, "maximum_color_change"),
          elapsed_ms: this._readField(reportPtr, R, "elapsed_ms"),
          converged: !!this._readField(reportPtr, R, "converged"),
        },
        problem_size: { chains: chainCount, control_points: totalControls, samples: totalSamples },
      };
    } finally {
      this._free(reportPtr);
      this._free(optPtr);
      for (const k of chainKeep) k.free();
      for (const k of keepalive) k.free();
    }
  }

  // ---- /api/defaults ----

  defaults() {
    const readOptions = (layoutName, defaultFn, enumFields) => {
      const ptr = this._malloc(this._structSize(layoutName));
      try {
        this.Module[defaultFn](ptr);
        const out = {};
        for (const [name, field] of Object.entries(BEZOPT_LAYOUT[layoutName].fields)) {
          let value = this._readField(ptr, layoutName, name);
          if (enumFields && enumFields[name]) {
            const mapping = enumFields[name];
            value = Object.keys(mapping).find(k => mapping[k] === value) || value;
          } else if (field.type === "i32" && /preserve|reproject|refine|optimize_/.test(name)) {
            value = !!value;
          }
          out[name] = value;
        }
        return out;
      } finally {
        this._free(ptr);
      }
    };
    return {
      options: readOptions("bezopt_options", "_wasm_default_options",
        { normalization: OPTIMIZER_NORMALIZATION_MODES }),
      preprocessor_options: readOptions("bezopt_preprocess_options", "_wasm_default_preprocess_options",
        { criterion: PREPROCESS_CRITERIA }),
      fitter_options: readOptions("bezopt_fit_options", "_wasm_default_fit_options", null),
      raster_options: readOptions("bezopt_raster_options", "_wasm_default_raster_options",
        { color_space: RASTER_COLOR_SPACES }),
      raster_optimizer_options: readOptions("bezopt_raster_optimize_options", "_wasm_default_raster_optimize_options",
        { color_space: RASTER_COLOR_SPACES, geometry_solver: RASTER_GEOMETRY_SOLVERS,
          block_schedule: RASTER_BLOCK_SCHEDULES, normalization: RASTER_NORMALIZATION_MODES }),
    };
  }
}

// Singleton for the page.
window.BezoptWasm = BezoptWasm;
window.BezoptWasmError = BezoptWasmError;

